version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - my_net
  api:
    image: hackaton-worktime-management:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - my_net

networks:
  my_net:
    driver: bridge