server:
  port: 8080

spring:
  datasource:
    drive-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/hackaton_company_db
#  rabbitmq:
#    host: ${RABBIT_HOST:localhost}
#    port: 5672
#    username: ${RABBIT_USERNAME:guest}
#    password: ${RABBIT_PASSWORD:guest}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  logging:
    level:
      root: ERROR
      org.springframework: ERROR

jwt:
  # secret: ${JWT_TOKEN_SECRET}
  secret: jwt-secret