name: hackaton-worktime-management-CICD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Build:
    name: Build App
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Project and Generate Docker Image
      run: mvn clean install -DskipTests --file pom.xml
   
    - name: Push Image to DockerHub
      run: mvn dockerfile:push

  
  DeployEKS:
      name: Deploy on EKS
      needs: Build
      runs-on: ubuntu-latest
     
      steps:
   
      - uses: actions/checkout@v3
 
      - name: Configurando Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
 
      - name: Kubectl Tool Setup
        uses: Azure/setup-kubectl@v3
 
      - run: aws sts get-caller-identity
       
      - run: aws eks update-kubeconfig --region us-east-1 --name fastfood-management-cluster

      - run: kubectl apply -k k8s
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' 

 
